- .env.example
- .gitignore
- app/Markdown/Parser.php
- config.php
- netlify.toml
- source/_assets/css/main.css
- source/_categories/javascript.md
- source/_categories/laravel.md
- source/_categories/php.md
- source/_layouts/category.blade.php
- source/_layouts/post.blade.php
- source/_partials/_categories.blade.php
- source/_partials/_header.blade.php
- source/_partials/_post-card.blade.php
- source/_posts/prevent-updating-or-saving-of-laravel-models.md
- source/_posts/what-is-alpine-js.md
- source/admin/config.yml
- source/categories.blade.php
- source/index.blade.php
- source/timeline.blade.php
This PR adds support for post categories. There's probably a better way of handling the filtering, but it's static so who cares.
To do list:
> Add support for post categories

- source/_partials/_header.blade.php
- source/articles.blade.php
- source/index.blade.php
Closes #22 . New articles page can be found at https://ryangjchandler.co.uk/articles
> Add dedicated articles page

- source/_layouts/post.blade.php
- source/_partials/_post-pagination.blade.php
- source/_posts/prevent-updating-or-saving-of-laravel-models.md
Closes #26 . Design is a bit jarring, but will do for now.
> Added next and previous links to posts

- tasks/deploy.sh
> Colours for deploy script

- app/helpers.php
- composer.json
- source/_layouts/post.blade.php
- source/_partials/_post-archived-notice.blade.php
- source/_posts/easily-format-your-titles.md
> Added support for archiving articles

- package.json
- resources/css/main.css
- resources/views/layouts/category.blade.php
- resources/views/layouts/master.blade.php
- resources/views/layouts/post.blade.php
- resources/views/partials/_footer.blade.php
- resources/views/partials/_header.blade.php
- resources/views/partials/_post-card.blade.php
- resources/views/partials/_post-pagination.blade.php
- resources/views/partials/_timeline-entry.blade.php
- resources/views/partials/_webmentions.blade.php
- source/articles.blade.php
- source/categories.blade.php
- source/index.blade.php
- source/timeline.blade.php
- tailwind.config.js
- webpack.mix.js
- yarn.lock
Closes #16 . Uses Alpine to add class to body at run time.
> Added dark mode to site

- app/Models/Article.php
- app/Nova/Article.php
- app/Support/Markdown/MarkdownServiceProvider.php
- database/migrations/2020_10_01_101911_add_show_toc_column_to_articles_table.php
- package.json
- resources/css/app.css
- resources/css/components/toc.css
- resources/views/articles/show.blade.php
- yarn.lock
> feature(table of contents)

- app/Support/Markdown/MarkdownServiceProvider.php
- resources/css/components/markup.css
- resources/css/components/toc.css
- tailwind.config.js
This PR styles the new heading permalinks.
> style(headling permalinks)

- resources/css/components/markup.css
> style(blockquotes)

- resources/views/layouts/partials/header.blade.php
- resources/views/pages/talks.blade.php
- routes/web.php
> feature(talks page): add page

- app/Models/Ad.php
- app/Models/Presenters/AdPresenter.php
- app/Nova/Ad.php
- bootstrap/helpers.php
- database/factories/AdFactory.php
- database/migrations/2020_10_20_080449_create_ads_table.php
- resources/css/app.css
- resources/css/components/ads.css
- resources/views/articles/show.blade.php
- resources/views/layouts/app.blade.php
- tests/Feature/AdTest.php
> feature: dynamic ad support

- app/Http/Middleware/RedirectIfNotPublished.php
- app/Nova/Article.php
- database/factories/ArticleFactory.php
- routes/web.php
- tests/Feature/ArticleTest.php
> feature(article preview): build functionality

- app/Http/Controllers/ArticleOgImageController.php
- resources/views/articles/og-image.blade.php
> fix(og images): text not being centered

- resources/views/components/newsletter.blade.php
> swapped to fortnightly

- app/Models/Article.php
- app/Nova/Article.php
- database/migrations/2020_11_07_154413_add_show_series_title_in_og_image_column_to_articles_table.php
- resources/views/articles/og-image.blade.php
> fix: series title in og_image

- public/mix-manifest.json
- resources/views/articles/show.blade.php
> feature: add end of article banner for twitter

- app/Models/Article.php
> fix(rss): use empty string when excerpt is null

- app/Support/Markdown/MarkdownServiceProvider.php
- public/mix-manifest.json
- public/static/theme.css
- resources/css/components/markup.css
- resources/syntax/blade.json
- resources/views/articles/show.blade.php
Closes #142.
See https://gist.github.com/ryangjchandler/f939b4105cf665e564df638d93e8c7d7 for more details.
> feature(highlighting): add support for blade using custom syntax

- app/Filament/Resources/PageResource.php
- app/Filament/Resources/PageResource/Pages/CreatePage.php
- app/Filament/Resources/PageResource/Pages/EditPage.php
- app/Filament/Resources/PageResource/Pages/ListPages.php
> feature: support editing pages

- app/Models/Page.php
- app/Models/Post.php
> fix: clear content cache after update

- app/Filament/Resources/ByteResource.php
- app/Filament/Resources/ByteResource/Pages/CreateByte.php
- app/Filament/Resources/ByteResource/Pages/EditByte.php
- app/Filament/Resources/ByteResource/Pages/ListBytes.php
- app/Models/Byte.php
- app/Providers/AppServiceProvider.php
- config/features.php
- content/bytes/a-clamp-function-for-php.md
- resources/views/bytes/index.blade.php
- resources/views/components/layouts/main.blade.php
- routes/web.php
> feature: bytes
